### ISSUE TITLE
Umlaut

### ISSUE THREAD

**Issue by polvanrijn** [davidagraf/doi2bib2#7]
Dear David,

doi2bib is super useful and it's great to use! It noticed when generating the cite key, it ignores German umlauts, e.g. if the first authors name is 'Günther' and the publication year is 2005, I expected guenther2005 (since ü is not allowed in the cite key), but not gnther2005.

Just so you know :-)

All the best,
Pol

**Comment by thurnherr** [comment]
Hi Pol,

Thanks for your message, I appreciate the input. For obvious reasons we want to get rid of special language characters in the cite key (the list is much longer than the three German Umlauts). As this is only the cite key and therefore not visible in the output, we decided to remove any special character rather than try to map it to an ASCII character. I suggest to edit it if the auto-generated cite key looks awkward.

Best,
Thomas
